### ISSUE TITLE
Active Scaffold not working with latest gem 'audited' in Rails 5.0

### ISSUE THREAD

**Issue by nishajgd** [activescaffold/active_scaffold#514]
When I use latest "audited" gem with version 4.3 , active_scaffold with version 3.2.20 (as latest does not support rails 5.0) along with rails 5.0 I am getting error in file

"/lib/active_scaffold/helpers/controller_helpers.rb"
the line is 
`controller.class_eval { helper_method :params_for, :conditions_from_params, :main_path_to_return, :render_parent?, :render_parent_options, :render_parent_action, :nested_singular_association?, :build_associated, :generate_temporary_id, :generated_id }`

If we add respond_to? block I feel this can be fixed.

Please suggest the way forward

**Comment by scambra** [comment]
Master branch must be used with rails 5.0, upgrade first, if still with error, please post exception, if I don't know the error I can't help

**Comment by nishajgd** [comment]
Hi Scambra,

Thank you for the timely support. I could upgrade and use the latest active_scaffold with master branch.While trying to upgrade my audited gem 4.2 to 4.3 (as 4.2 wont support Rails 5.0) I am getting the below error in active_scaffold

`bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:in `block in included': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:in `class_eval'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-d9b396492fc4/lib/active_scaffold/helpers/controller_helpers.rb:5:in `included'
`
I request your support on this.

**Comment by nishajgd** [comment]
Hi Scambra,

Can you please support to get this issue fixed. Audited and Active Scaffold are integral part of our current app. It would be much appreciated if you can support at this moment.

Thnaks in advance! :)

**Comment by scambra** [comment]
Are you using ActiveScaffold with rails api mode? I mean, do you have config.api_only = true in config/application.rb? In that case, is it ActiveScaffold useful for you? I would think there is no point in using ActiveScaffold for api only apps, but I could add support for it if it's worth

**Comment by nishajgd** [comment]
I am not using with rails api mode. But my application is mainly focused on apis. And we have few CRUD operations with ActiveScaffold. Can you make the fix for the same?

**Comment by scambra** [comment]
But you have controllers which inherit from ActionController::API instead of ActionController::Base. Do you have any controller which inherit from ActionController::Base? Or is every controller focused on apis?

**Comment by nishajgd** [comment]
My controllers are inherited from ApplicationController which is inherited from ActionController::Base

**Comment by scambra** [comment]
It doesn't make sense with error you get:
undefined method helper_method' for ActionController::API:Class

Can you provide a longer backtrace so I can see what controller is raising exception? According to error, that controller should be inheriting from ActionController::API.

**Comment by nishajgd** [comment]
Please find the whole backtrace

`/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/helpers/controller_helpers.rb:5:in `block in included': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/helpers/controller_helpers.rb:5:in `class_eval'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/helpers/controller_helpers.rb:5:in `included'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/engine.rb:8:in `include'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/engine.rb:8:in `block (2 levels) in <class:Engine>'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/bundler/gems/active_scaffold-996cfaf27b82/lib/active_scaffold/engine.rb:4:in `block in <class:Engine>'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/bitlasoft/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /work/ts/ts-agent/config/environment.rb:5:in `<top (required)>'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /work/ts/ts-agent/config.ru:3:in `block in <main>'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /work/ts/ts-agent/config.ru:in `new'
	from /work/ts/ts-agent/config.ru:in `<main>'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/bitlasoft/.rvm/gems/ruby-2.3.1@rails5.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'`

**Comment by scambra** [comment]
ActionController::API is being loaded, and it run lazy load hook used to include ControllerHelpers. I don't know why is being loaded if you don't use it, but I'm preventing to call helper_method in ActionController::API

**Comment by nishajgd** [comment]
Thanks for updating the code. It is working now!  :+1:
