### ISSUE TITLE
Chosen appears to stop working on v3.5

### ISSUE THREAD

**Issue by spatarel** [activescaffold/active_scaffold#610]
Gemfile:
```
gem 'active_scaffold', '~> 3.5', '>= 3.5.3'
gem 'chosen-rails', '~> 1.5.1'
```
(I also tried this with newer versions of chosen but got the same result)

When I try to create a new object the server outputs the following error:

```
Started GET "/tutor/companies/new?adapter=_list_inline_adapter" for 127.0.0.1 at 2019-01-18 00:18:57 +0200
Processing by Tutor::CompaniesController#new as JS
  Parameters: {"adapter"=>"_list_inline_adapter"}
  Rendered /home/dan/.rvm/gems/ruby-2.3.0/gems/active_scaffold-3.5.3/app/views/active_scaffold_overrides/_form_messages.html.erb (0.9ms)
NoMethodError: undefined method `templates' for nil:NilClass -- on the ActiveScaffold column = :templates in Tutor::CompaniesController
  Rendered /home/dan/.rvm/gems/ruby-2.3.0/gems/active_scaffold-3.5.3/app/views/active_scaffold_overrides/_form.html.erb (290.8ms)
  Rendered /home/dan/.rvm/gems/ruby-2.3.0/gems/active_scaffold-3.5.3/app/views/active_scaffold_overrides/_base_form.html.erb (305.0ms)
  Rendered /home/dan/.rvm/gems/ruby-2.3.0/gems/active_scaffold-3.5.3/app/views/active_scaffold_overrides/_create_form.html.erb (318.3ms)
Completed 500 Internal Server Error in 332ms (ActiveRecord: 0.0ms)


  
ActionView::Template::Error (undefined method `templates' for nil:NilClass):
    24:     <%= render_column(column, @record, renders_as, scope) %>
    25:   <% end %>
    26:   <% else -%>
    27:   <li class="form-element <%= 'required' if column.required? %> <%= column.form_ui %> <%= column_css_class %>">
    28:     <%= render_column(column, @record, renders_as, scope, !authorized) %>
    29:   </li>
    30:   <% end -%>
  
active_scaffold (3.5.3) lib/active_scaffold/helpers/form_column_helpers.rb:356:in `active_scaffold_plural_association_options'
active_scaffold (3.5.3) lib/active_scaffold/bridges/chosen/helpers.rb:15:in `active_scaffold_input_chosen'
active_scaffold (3.5.3) lib/active_scaffold/helpers/form_column_helpers.rb:21:in `active_scaffold_render_input'
active_scaffold (3.5.3) lib/active_scaffold/helpers/form_column_helpers.rb:10:in `active_scaffold_input_for'
active_scaffold (3.5.3) lib/active_scaffold/helpers/form_column_helpers.rb:180:in `form_attribute'
active_scaffold (3.5.3) lib/active_scaffold/helpers/form_column_helpers.rb:159:in `render_column'
...

```

It seems to me (or I may be wrong) that the issue is here:

/lib/active_scaffold/bridges/chosen/helpers.rb:
```
module FormColumnHelpers
  # requires RecordSelect plugin to be installed and configured.
  def active_scaffold_input_chosen(column, html_options)
    html_options[:class] << ' chosen'
    if column.association&.collection?
      associated_options, select_options = active_scaffold_plural_association_options(column)
```

/lib/active_scaffold/helpers/form_column_helpers.rb:
```
def active_scaffold_plural_association_options(column, record = nil)
  associated_options = record.send(column.association.name)
  [associated_options, associated_options | sorted_association_options_find(column.association, nil, record)]
end
```
Am I doing something wrong or is this a real issue?
Thank you!

**Comment by spatarel** [comment]
Thank you for fixing this! It works.
But now I have two more issues related to chosen. I will mention just one, for now:

I have a `:contract` column configured as such:
```
class Teachers::BillsController < TeacherController
  active_scaffold :bill do |conf|
    # ...
    conf.columns[:contract].form_ui = :chosen # :select
    conf.columns[:contract].clear_link
    conf.columns[:contract].update_columns = [:sponsorships]
    conf.columns[:contract].send_form_on_update_column = true
    # ...
  end
end
```

I also have a filter set on the `:sponsorships` column:
```
module Tutor::BillsHelper
  def options_for_association_conditions(association, record)
    if record.kind_of? Bill
      if association.name == :contract
        ['contracts.id IN
           (SELECT DISTINCT s.contract_id FROM sponsorships s
            LEFT JOIN contracts c ON (c.id = s.contract_id)
            LEFT JOIN sponsors sp ON (sp.id = c.sponsor_id)
            WHERE (sp.bill_always OR lesson_id IN
             (SELECT id FROM lessons
              WHERE EXTRACT(YEAR FROM date) = EXTRACT(YEAR FROM (NOW() - INTERVAL \'1 MONTH\'))
              AND EXTRACT(MONTH FROM date) = EXTRACT(MONTH FROM (NOW() - INTERVAL \'1 MONTH\'))))
            AND s.bill_id IS NULL)']
      end
    end
  end
end
```

The trouble is now I get this brand new error:
```
Rendering /home/dan/.rvm/gems/ruby-2.3.0/bundler/gems/active_scaffold-e48678c9e531/app/views/active_scaffold_overrides/render_field.js.erb
ArgumentError: You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`. -- on the ActiveScaffold column = :sponsorships in Teachers::BillsController
  Rendered collection of /home/dan/.rvm/gems/ruby-2.3.0/bundler/gems/active_scaffold-e48678c9e531/app/views/active_scaffold_overrides/_render_field.js.erb [1 times] (13.1ms)
  Rendered /home/dan/.rvm/gems/ruby-2.3.0/bundler/gems/active_scaffold-e48678c9e531/app/views/active_scaffold_overrides/render_field.js.erb (18.4ms)
Completed 500 Internal Server Error in 75ms (ActiveRecord: 5.9ms)


  
ActionView::Template::Error (You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`.):
    19:     crud_type = @record.new_record? ? :create : (readonly ? :read : :update)
    20:     active_scaffold_render_subform_column(column, scope, crud_type, readonly, !active_scaffold_config.subform.columns.names_without_auth_check.include?(column.name), @record)
    21:   else
    22:     render_column(column, @record, renders_as, scope)
    23:   end
    24: -%>
    25: 
```
Am I doing something wrong or is this a real issue?
Thank you!
