### ISSUE TITLE
not able to get any object in dynamic_parameters with action_links

### ISSUE THREAD

**Issue by pbharadiya** [activescaffold/active_scaffold#452]
Hello,

I am facing one issue using dynamic_parameters option with action_links.
Below is my code.
<pre><code>config.action_links.add "download_csv", :label => 'Download CSV', :type => :collection, :page => true, :dynamic_parameters => Proc.new {{:dynamic => current_action}}</code></pre>

I have used below code in helper file.
<pre><code>def current_action
  params[:action]
end
</code></pre>

I am getting this error -
<code>undefined local variable or method `current_action' for #<ActiveScaffold::Config::Core:0x007f9075c93b98></code>

I need current action for every request along with action link as a parameter which will be dynamic.
P.S Even if I get request object or params in the dynamic_parameters, that will be suffice.
Using active_scaffold 3.3.3 with rails 3.2.12 & ruby 1.9.3

Any help is highly appreciated please.

Thanks.

**Comment by pbharadiya** [comment]
Got the work around.

I overrided method in helper file as below.
<pre><code>def render_action_link(link, record=nil, html_options = {})
  link.dynamic_parameters = Proc.new {{:method => params[:action]}} if link.action.to_sym == :download_csv
  super
end</code></pre>

It worked like a charm for me!

**Comment by scambra** [comment]
glad to hear you could workaround, but bug is there, so I'm reopening it

proc is being run on original binding, which doesn't make sense, but I never realized it because I always used with record parameter, to check record attributes.

**Comment by scambra** [comment]
I have tried but I can't reproduce, it works in 3.4.30, probably from 3.4.21

Also, you don't need to define current_action, you have action_name which returns the same
