### ISSUE TITLE
rails 6 support?

### ISSUE THREAD

**Issue by Raj-Kumar-P** [activescaffold/active_scaffold#624]
active_scaffold gem supports to rails 6?
I have trying to followed the steps based on the documentation.  When I run 

> rails g active_scaffold:install

raise an error. like 

>  missing  app/assets/javascripts/application.js

> JS file app/assets/javascripts/application.js is required for ActiveScaffold

**Comment by DRSisco** [comment]
Note: https://github.com/rails/rails/commit/4838c1716a0340137d858fab49bf460e23be5a4b#diff-ba42d3f140343c52e230d735173afa34 removed `app/assets/javascript` from the default template when generating a project. (For Rails >= 6.0) 

@Raj-Kumar-P did you try adding the above file from your error message? 
You will also want to include that file on any page that would use active_scaffold. 
```rb
    #views/layouts/application.html.erb
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
```

**Comment by scambra** [comment]
I haven't used rails 6 yet, but I have fixed one failing test.

There are 2 more tests failing, but they are related to tableless support, which I don't think many people use.

Generator will still fail because there is no app/assets/javascripts/application.js file, and looks like javascript_include_tag is not used in default layout. How should a file be added when using webpacker in rails 6? Or must generator create a new app/assets/javascripts/application.js and keep using asset pipeline instead of using webpacker?

**Comment by DRSisco** [comment]
If the developer wants to use either webpacker or sprockets, then we should be supportive of that. 

What I've seen a lot of gems doing is actually making instructions to either option as part of their readme. 

For sprockets you will potentially need to add that JS file:
Sprokets - `app/asset/javascript/application.js`
```js
  //= require active_scaffold
```
And then reference that application.js file with the javascript include tag I posted above.
However sprokets is still the default pipeline for stylesheets, keeping the css the same.

OR 

For Webpacker you will need to post a node module.
Webpacker - `app/javascript/packs/application.js` 
```js
  require("active_scaffold")
```

---

Also, I am not sure I agree with the generator approach as it makes assumptions on part of the user. For example the generator would load all the AS assets for every page and that seems excessive. 
Personally when using active_scaffold I override list.html.erb with the following:
```
<% unless nested? %>
  <%= javascript_include_tag 'active_scaffold' %>
  <%= stylesheet_link_tag 'active_scaffold_layout' %>
  <%= stylesheet_link_tag 'active_scaffold_images' %>
  <%= stylesheet_link_tag 'active_scaffold_extensions' %>
  <%= stylesheet_link_tag 'active_scaffold_colors' %>
<% end %>
<%= render :partial => 'list_with_header' -%>
```
But to be my own devil's advocate I suppose a more advanced user could figure that out on their own and it really isn't a big deal to have all these assets loaded on every page.

**Comment by dennisbulgatz** [comment]
Is there a guide to stand up a new rails 6 app from scratch that has been tested?

**Comment by scystephen** [comment]
I have gotten fairly far in building a Rails 6 app where the generators work but the app still fails.

Here are the exact steps I've taken (on a Mac):
---
gem install rails -v 6.0.3.1
rails _6.0.3.1_ new RailsSixZero \
--database=mysql \
--skip-git \
--skip-action-mailer \
--skip-action-mailbox \
--skip-action-text \
--skip-active-storage \
--skip-action-cable \
--no-skip-sprockets \
--skip-spring \
--skip-listen \
--skip-javascript \
--skip-turbolinks \
--skip-test \
--skip-system-test \
--skip-bootsnap \
--skip-bundle \
--skip-webpack-install
cd RailsSixZero
echo "
gem 'active_scaffold', '3.6.0.pre'" >> Gemfile
bundle install
mkdir -p app/assets/javascripts
touch app/assets/javascripts/application.js
echo "//= require jquery
//= require jquery_ujs
//= require_tree ." >> app/assets/javascripts/application.js
echo "//= link_directory ../javascripts .js" >> app/assets/config/manifest.js
---

All of this gets the app to the point where it's got a very Rails 5.x javascript setup.

The final step is to edit the file app/views/layouts/application.html.erb and add <%= javascript_include_tag 'application' %> after <%= csp_meta_tag %>

Get the app running with:
bundle exec rails db:create
bundle exec rails g active_scaffold:install
bundle exec rails g active_scaffold:resource ActiveScaffoldTest test_string:string
bundle exec rails db:migrate
bundle exec rails s

Going to http://localhost:3000/active_scaffold_tests I get the error:
NoMethodError (undefined method `each_key' for #<ActiveScaffold::DataStructures::Sorting:0x00007ff46cc766f0>):

**Comment by scambra** [comment]
You should use master branch instead of 3.6.0.pre, it has many fixes, although I don't know if there is still something not working with rails 6.0

**Comment by scystephen** [comment]
If I start Rails 5.2, I can build an app and use ActiveScaffold 3.5.2, but building active scaffold from a git and including the gem by putting the following in Gemfile:

gem 'active_scaffold', '3.6.0.pre', path: "custom_gems" 

After running 'bundle install' I get the following when I try to install active scaffold:
bundle exec rails g active_scaffold:install
Could not find generator 'active_scaffold:install'. Maybe you meant 'active_record:model', 'active_record:migration' or 'css:scaffold'
Run `rails generate --help` for more options.

**Comment by jasonfb** [comment]
the standard way is to create a pack associated with the section of your Rails application where you will use Activescaffold.. For example, if you use Active scaffold in your Admin area, you Admin controllers would have 

```layout "admin"```

Then, your `admin.erb`  would load the pack, a pack specific to active scaffold or an "omnibus" pack for all of the admin javascript, which includes the active scaffold. it would be referenced from the layout like so
```
<%=javascript_pack_tag 'admin' %>

````

**Comment by scambra** [comment]
I have made some progress in supporting adding active_scaffold into pack file, in webpack branch.
You can test in rails 6 project with yarn add https://github.com/activescaffold/active_scaffold#webpack

Node module has dependency on jquery, and it imports jquery in active_scaffold module. It isn't finished, but at least I got it working without error on page load, and basic JS actions work. I haven't added dependency on jquery-ui yet, but I will.

Previously, with assets pipeline, js file was .js.erb and it included JS files from other ActiveScaffold plugins (batch or sortable plugins), and javascript for enabled bridges (chosen, record_select, tiny_mce, calendar_date_select but it's old and prototype related, I will remove it eventually). I think it can't be done with webpack, so batch or sortable plugins will have to add themselves to pack file, and I will check if bridges can be included by default, or maybe user need to add them to pack file if they use the bridge.

I haven't work much in install generator yet. I have just disabled adding javascript line from generator, but I will re-add later. When I add it, it will check if javascript assets exist to add old line there, in other case, it will add require('activescaffold') to pack/application.js. I'm thinking in run yarn add active_scaffold command too, although it should install same version as gem, or version from git, so I guess it should find used version from bundle. I can probably add options such as skip-yarn and skip-webpack. What do you think?

**Comment by dennisbulgatz** [comment]
Rails 6 seems to be working fine with the master branch.  Any plans to release a gem based on current master?

**Comment by scambra** [comment]
I could release pre2 or rc1, but I would like to release once changes from webpack branch are finished.

Also, I think there are issues with sorting, I haven't tested yet, but this deprecation warning in rails 5.2 was reported in google group:
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "`pers_sports`.`id` ASC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in append_to_query at /vendor/bundle/ruby/2.6.0/bundler/gems/active_scaffold-d6756e1f3eb5/lib/active_scaffold/finder.rb:539)

So it's possible sorting is not working with rails 6.

**Comment by scambra** [comment]
Rails 6 finally didn't deprecate that usage, it will be deprecated in 6.1, and it affected when user set sort_by with something which is not column or table.column, such as sql functions. Anyway, I have fixed it and I'm releasing rc1.

**Comment by dennisbulgatz** [comment]
Thanks Sergio!  You support on this library has been fantastic over the years.  Not sure who will carry the torch when you retire from the AS leadership.

**Comment by markmcdonald51** [comment]
Just successfully added: yarn add https://github.com/activescaffold/active_scaffold#webpack
then added to Gemfile:
gem 'active_scaffold', git: 'https://github.com/activescaffold/active_scaffold', branch: 'webpack' 

no setup install as per instructions above and started rails s and get this:

from /home/mark/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/active_scaffold-a6e33a974f90/lib/active_scaffold/engine.rb:41:in `block in <class:Engine>'
/home/mark/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.1/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `assets' for #<Rails::Engine::Configuration:0x000055ec47661140> (NoMethodError)

Thanks again for all the great time and thought you put into this Sergio.

**Comment by markmcdonald51** [comment]
Can someone who has got this gem working with Rails6  post some simple documentation as to how to get AS working? The gem branch stated above doesn't seem to compile. I really want to use this for a project I am working on. Thanks in advance!

**Comment by scambra** [comment]
webpack branch is work in progress, I didn't get that error, but I haven't get everything working yet with packs, so you should use master branch and use assets pipeline as @DRSisco explained https://github.com/activescaffold/active_scaffold/issues/624#issuecomment-612399008

**Comment by gregschmit** [comment]
Closing as AS works in rails 6; webpacker was removed from rails (kept alive by shakapacker) in 7, so migrating to webpacker assets would be a step backwards.
