### ISSUE TITLE
Rails 5.2: undefined local variable or method `active_scaffold_config'

### ISSUE THREAD

**Issue by Nowaker** [activescaffold/active_scaffold#656]
After bumping from Rails 5.1 to 5.2, and from Active Scaffold 3.5.x to 3.6.0.rc2, I'm getting this:

> undefined local variable or method `active_scaffold_config' for #<#<Class:0x00007f8aa53a4378>:0x00007f8aa53f5bd8>

I use `active_scaffold_config` in HAML.

**Comment by Nowaker** [comment]
If I change `active_scaffold_config` to `controller.active_scaffold_config`, I'm getting an exception `undefined method `user' for nil:NilClass` in `active_scaffold (3.6.0.rc2) lib/active_scaffold/core.rb:19:in `active_scaffold_config'`. (First frame inside `def active_scaffold_config` so nothing else to share here)

**Comment by Nowaker** [comment]
Okay, I think this is the correct way to check whether a given controller is an ActiveScaffold-enabled controller or not:

```diff
-      - unless active_scaffold_config.nil?
+      - if defined? active_scaffold_config
```

**Comment by scambra** [comment]
There is a method uses_active_scaffold?, it's a clases method so you should use controller.class.uses_active_scaffold?

**Comment by Nowaker** [comment]
@scambra Even better, thanks for sharing!
