### ISSUE TITLE
Field highlight (i.e. red border) missing for foreign key (FK) validation of uniqueness.

### ISSUE THREAD

**Issue by JonasBang** [activescaffold/active_scaffold#156]
If you make a model validation of uniqueness for a FK you need to use the full column name with "_id" postfix, otherwise you get a "NoMethodError (undefined method `text?' for nil:NilClass)" error.

Example of how it works in rails 3.1:
class PlatformVersion < ActiveRecord::Base
  belongs_to :platform
  validates :platform, :presence => {:message => 'must be specified'}
  validates :platform_id, :uniqueness => {:message => 'has a version already'}
end

The validation of presence works without the "_id" postfix, but not the validation of uniqueness. This validation of uniqueness is needed if you have a "has_one" relation.

FYI: For text columns both validation of presence and uniqueness works without the "_id" postfix. So this is a special case for "has_one" FK validations it seems.

Problem in ActiveScaffold is that only validations defined without the "_id" postfix will generate the field highlight (i.e. red border) when failing.

So in the example above, if you try to save the record without selecting a Platform you get a validation fail message and the Platform dropdown is highlighted with a red border. But if you select a Platform which already has a PlatformVersion you only get the validation fail message and not the dropdown red border highlight.

In an example like this it is probably a minor issue, but if you have a whole page of dropdowns to select for a record, it really is helpful to have that red border highlight of the failing columns. And for consistency it makes sense to look into this as well.
