### ISSUE TITLE
undefined method 'merge' for nil:NilClass on Rails upgrade

### ISSUE THREAD

**Issue by voodoologic** [activescaffold/active_scaffold#340]
I am running into errors when updating from Rails 3.0 to 3.2.17.  Once the upgrade is in place and I have active_scaffold 3.3.3 in place, my configuration fails.
I am hoping somebody has come across this before or knows how to address this problem.

Error:

undefined method `merge' for nil:NilClass

/vagrant/rails/shared/bundle/ruby/1.9.1/gems/active_scaffold-3.3.3/app/views/active_scaffold_overrides/_list_record.html.erb

10:     <% authorized = record.authorized_for?(:crud_type => :read, :column => column.name) -%>
11:     <% column_value = authorized ? get_column_value(record, column) : active_scaffold_config.list.empty_field_text -%>
12: 
13:     <%= content_tag :td, column_attributes(column, record).merge(:class => column_class(column, column_value, record)) do %>
14:       <%= authorized ? render_list_column(column_value, column, record) : column_value %>
15:     <% end %>
16:   <% end -%>

column_attributes(column, record) returns nil thus the merge fails.

A binding.pry statement inside the file reveals:

[2] pry(#<#Class:0xc059fcc>)> column  
=> #<ActiveScaffold::DataStructures::Column:0xb524cec
 @active_record_class=
  Webcast(id: integer, user_id: integer, title: string, session_title: string, body_copy: text, meta_description: text, meta_keywords: text, permalink: string, primary_encoder_entrypoint: string, secondary_encoder_entrypoint: string, client_stream: string, stream_name: string, stream_status: string, start: datetime, background_color: string, background_top_color: string, background_bottom_color: string, button_color: string, button_color_hover: string, font_color: string, font_family: string, button_font_color: string, highlight_color: string, bar_chart_color: string, tech_support_email: string, client_event_description_url: string, twitter_url: string, facebook_url: string, linkedin_url: string, flickr_url: string, aspect_ratio: string, secondary_aspect_ratio: string, logo_file_name: string, logo_content_type: string, logo_file_size: integer, logo_updated_at: datetime, splash_file_name: string, splash_content_type: string, splash_file_size: integer, splash_updated_at: datetime, created_at: datetime, updated_at: datetime, skin_id: integer, user_required: string, speaker_id: integer, moderator_id: integer, disable_splash: boolean, loop_teasers: boolean, controlled_playback: boolean, fms_ip: string, blur_skin: boolean, banner_color: string, domain_id: integer, current_composition_state: text, recording_offset_millis: integer, when_recorded: datetime, start_in_seconds: decimal, thumbnail_file_name: string, thumbnail_content_type: string, thumbnail_file_size: integer, thumbnail_updated_at: datetime, production_at: datetime, legacy: boolean, auto_guide: boolean),
 @allow_add_existing=true,
 @associated_limit=3,
 @associated_number=true,
 @association=nil,
 @autolink=false,
 @column=nil,
 @css_class="",
 @list_method=:format_column_value,
 @name=:webcast_console,
 @number=nil,
 @options={},
 @required=false,
 @search_sql=nil,
 @select_columns=nil,
 @send_form_on_update_column=nil,
 @show_blank_record=true,
 @sort=false,
 @table="webcasts",
 @tableless=nil,
 @weight=300>

[3] pry(#<#Class:0xc059fcc>)> record  
=> #<Webcast id: 615, user_id: nil, title: "Roasted Red Snapper", session_title: "Roasted Red Snapper", body_copy: "Andrew Zimmern is a James Beard Award-winning TV pe...", meta_description: "Andrew Zimmern is a James Beard Award-winning TV pe...", meta_keywords: "Andrew Zimmern is a James Beard Award-winning TV pe...", permalink: "snapper", primary_encoder_entrypoint: nil, secondary_encoder_entrypoint: nil, client_stream: nil, stream_name: nil, stream_status: "Slate", start: nil, background_color: "#000000", background_top_color: "#000000", background_bottom_color: "#29AAE3", button_color: "#29AAE3", button_color_hover: "#000000", font_color: "#FFFFFF", font_family: "Arial,Helvetica,sans-serif", button_font_color: "#FFFFFF", highlight_color: "#FD0E0F", bar_chart_color: "#29AAE3", tech_support_email: "example@onetotheworld.com", client_event_description_url: nil, twitter_url: "https://twitter.com/andrewzimmern", facebook_url: "https://www.facebook.com/AndrewZimmern", linkedin_url: "http://www.linkedin.com/pub/andrew-zimmern/45/a7b/b...", flickr_url: nil, aspect_ratio: "16:9", secondary_aspect_ratio: "None", logo_file_name: nil, logo_content_type: nil, logo_file_size: nil, logo_updated_at: nil, splash_file_name: nil, splash_content_type: nil, splash_file_size: nil, splash_updated_at: nil, created_at: "2013-06-14 19:10:54", updated_at: "2013-12-09 18:37:07", skin_id: 221, user_required: "None", speaker_id: 360, moderator_id: 360, disable_splash: nil, loop_teasers: nil, controlled_playback: false, fms_ip: nil, blur_skin: false, banner_color: nil, domain_id: 42, current_composition_state: {"teaserLoop"=>false, "left"=>nil, "onDemand"=>true, "end"=>false, "cuts"=>nil, "when"=>nil, "full"=>nil, "right"=>nil, "tickerMessage"=>nil, "overlay"=>nil}, recording_offset_millis: 189000, when_recorded: nil, start_in_seconds: nil, thumbnail_file_name: "Thumbnail.png", thumbnail_content_type: "image/png", thumbnail_file_size: 166566, thumbnail_updated_at: "2013-06-17 19:06:51", production_at: "2013-06-18 00:00:00", legacy: false, auto_guide: false>

I have commented out every helper method for the Webcast class.  In addition, I can make the page render only if I remove every configuration line.

Here is the full stack trace:

active_scaffold (3.3.3) app/views/active_scaffold_overrides/_list_record.html.erb:13:in `block in __vagrant_rails_shared_bundle_ruby_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_record_html_erb__1029635001_108056690'
active_scaffold (3.3.3) app/views/active_scaffold_overrides/_list_record.html.erb:9:in`each'
active_scaffold (3.3.3) app/views/active_scaffold_overrides/_list_record.html.erb:9:in `__vagrant_rails_shared_bundle_ruby_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_record_html_erb__1029635001_108056690'
actionpack (3.2.17) lib/action_view/template.rb:145:in`block in render'
activesupport (3.2.17) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.17) lib/action_view/template.rb:143:in`render'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in `block in profile_method'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:351:in`block in collection_with_template'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:348:in `each'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:348:in`collection_with_template'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:250:in `render_collection'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:234:in`block in render'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:233:in`render'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:15:in`render'
actionpack (3.2.17) lib/action_view/helpers/rendering_helper.rb:24:in `render'
active_scaffold (3.3.3) lib/active_scaffold/extensions/action_view_rendering.rb:122:in`render_with_active_scaffold'
haml (4.0.5) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
active_scaffold (3.3.3) app/views/active_scaffold_overrides/_list.html.erb:28:in`__vagrant_rails_shared_bundle_ruby_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_html_erb__754595503_107143740'
actionpack (3.2.17) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.17) lib/active_support/notifications.rb:125:in`instrument'
actionpack (3.2.17) lib/action_view/template.rb:143:in `render'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in`block in profile_method'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:238:in`block in render'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:237:in`render'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:15:in`render'
actionpack (3.2.17) lib/action_view/helpers/rendering_helper.rb:24:in `render'
active_scaffold (3.3.3) lib/active_scaffold/extensions/action_view_rendering.rb:122:in`render_with_active_scaffold'
haml (4.0.5) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
active_scaffold (3.3.3) app/views/active_scaffold_overrides/_list_with_header.html.erb:34:in`__vagrant_rails_shared_bundle_ruby_______gems_active_scaffold_______app_views_active_scaffold_overrides__list_with_header_html_erb__55680229_96948920'
actionpack (3.2.17) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.17) lib/active_support/notifications.rb:125:in`instrument'
actionpack (3.2.17) lib/action_view/template.rb:143:in `render'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in`block in profile_method'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:238:in`block in render'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in`instrument'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.17) lib/action_view/renderer/partial_renderer.rb:237:in`render'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:15:in`render'
actionpack (3.2.17) lib/action_view/helpers/rendering_helper.rb:24:in `render'
active_scaffold (3.3.3) lib/active_scaffold/extensions/action_view_rendering.rb:122:in`render_with_active_scaffold'
haml (4.0.5) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
active_scaffold (3.3.3) app/views/active_scaffold_overrides/list.html.erb:1:in`__vagrant_rails_shared_bundle_ruby_______gems_active_scaffold_______app_views_active_scaffold_overrides_list_html_erb___1029248960_105362720'
actionpack (3.2.17) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.17) lib/active_support/notifications.rb:125:in`instrument'
actionpack (3.2.17) lib/action_view/template.rb:143:in `render'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in`block in profile_method'
actionpack (3.2.17) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.17) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
actionpack (3.2.17) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
actionpack (3.2.17) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
actionpack (3.2.17) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.17) lib/action_view/renderer/template_renderer.rb:18:in`render'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.17) lib/action_view/renderer/renderer.rb:17:in`render'
actionpack (3.2.17) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.17) lib/action_controller/metal/streaming.rb:225:in`_render_template'
actionpack (3.2.17) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.17) lib/action_controller/metal/renderers.rb:28:in`render_to_body'
actionpack (3.2.17) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.17) lib/abstract_controller/rendering.rb:88:in`render'
actionpack (3.2.17) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
activesupport (3.2.17) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/vagrant/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/benchmark.rb:295:in`realtime'
activesupport (3.2.17) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:40:in`block in render'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.17) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:39:in `render'
active_scaffold (3.3.3) lib/active_scaffold/extensions/action_controller_rendering.rb:14:in`render_with_active_scaffold'
active_scaffold (3.3.3) lib/active_scaffold/actions/list.rb:33:in `list_respond_to_html'
active_scaffold (3.3.3) lib/active_scaffold/actions/core.rb:190:in`block (3 levels) in respond_to_action'
actionpack (3.2.17) lib/action_controller/metal/mime_responds.rb:196:in `call'
actionpack (3.2.17) lib/action_controller/metal/mime_responds.rb:196:in`respond_to'
active_scaffold (3.3.3) lib/active_scaffold/actions/core.rb:186:in `respond_to_action'
active_scaffold (3.3.3) lib/active_scaffold/actions/list.rb:25:in`list'
active_scaffold (3.3.3) lib/active_scaffold/actions/list.rb:9:in `index'
actionpack (3.2.17) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.2.17) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.17) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.2.17) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.17) lib/active_support/callbacks.rb:579:in`_run__220186472__process_action__853674656__callbacks'
activesupport (3.2.17) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.17) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.17) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.17) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.17) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.17) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.17) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.17) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.17) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.17) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (3.2.17) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.17) lib/abstract_controller/rendering.rb:45:in`process'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiling_methods.rb:108:in `block in profile_method'
actionpack (3.2.17) lib/action_controller/metal.rb:203:in`dispatch'
actionpack (3.2.17) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.17) lib/action_controller/metal.rb:246:in`block in action'
actionpack (3.2.17) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.17) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
actionpack (3.2.17) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in`block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in`call'
actionpack (3.2.17) lib/action_dispatch/routing/route_set.rb:608:in `call'
lib/ottw_middleware/host_logger.rb:17:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in`call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/flash.rb:242:in`call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.17) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.2.17) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.17) lib/active_support/callbacks.rb:405:in `_run__1002375655__call__47989742__callbacks'
activesupport (3.2.17) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.17) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.17) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.17) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.17) lib/rails/rack/logger.rb:32:in`call_app'
railties (3.2.17) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.17) lib/active_support/tagged_logging.rb:22:in`tagged'
railties (3.2.17) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.17) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.17) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in`call'
actionpack (3.2.17) lib/action_dispatch/middleware/static.rb:63:in `call'
rack-mini-profiler (0.9.1) lib/mini_profiler/profiler.rb:300:in`call'
railties (3.2.17) lib/rails/engine.rb:485:in `call'
railties (3.2.17) lib/rails/application.rb:231:in`call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.17) lib/rails/rack/log_tailer.rb:17:in`call'
rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
/home/vagrant/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
/home/vagrant/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/home/vagrant/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'
